### PR TITLE
WIP: Implement docker

### PR DESCRIPTION
**Pull request by mpiot**
This PR add:
 - docker
 - Webpack to manage assets

In the public directory, there is 2 folders:
 - examples (to remove ?)
 - assets (the major parts contains images: avatar, bg, img, logo, then it should be moved to /assets/img, maybe rename/remove some folders ? Don't keep, then change the `asset()` call everywhere ? What about the bornes folder ? It contain: images, css, js.

### CODE REVIEW

**Comment by Dannebicque** [comment]
I merge this PR (I think...)

I have add my js files in assets/js/partials and the others files that I create... Maybe not in the good place ?
Assets looks good, but many error due to javascript. Maybe not in good place ? I try to resolve these problems

**Comment by mpiot** [comment]
Oups, the PR was not ready to merge, that's why I've use the WIP keyword (Work In Progress).

Then, you must fix some things after the merge. All assets shoud be in /assets/js, or scss, or img folder. But they're not handle by default: images yes, but all js files must be called in the app.js file (`require("myCustomFile")`). Alls cutom css should be add in the app.scss file too (or others, but specified in the webpack.encore.js file.

**Comment by Dannebicque** [comment]
No problem. I just wanted to see how everything was rearranged. I think I've coined the problem, which comes from the theme. The app.min, seems to wait for a script tag in the html file and look where is the core.min library by reading the "src" attribute. 

But with the "require" it does not necessarily work anymore. I will try to understand what this app does and see how to modify it to work in a webpack environment.

**Comment by MrGabigoo** [comment]
Just asking because I’m curious — is the use of Docker really fit for this project ? As far as I know from previous knowledge of this application it isn’t “designed to be scaled” per se, and I wouldn’t really consider scaling to be that necessary given the context in which it is used. 

Furthermore, do the advantages of this solution really overweigh the performance and complexity overhead?  

Again these are real questions, I’m not just chiming in to criticize any of this. In case you’re wondering, the reason why I’m asking these questions is because I’ve experimented a bit with docker for my own projects and I’ve found it to be rather annoying to deploy to production and all in all not noticeably more convenient than my previous deploy strategy on a rather vanilla NGINX/PHP/MariaDB server

**Comment by mpiot** [comment]
Hi @MrGabigoo :-)

IMO we can use Docker for both, dev and prod environment, in fact Docker is almost essential on project that need to be scaled in the time. But it's interesting to use it for dev too.

 - Don't install any daemon dependencies on your machine for dev
 - Have the same version on your machine than used by the project (PHP 5.7, 7.0, 7.1, 7.3.2, 7.3.3, idem for other daemons). => between developers, production server (use the same version image than the server in this case, just replace a heavy Vagrant)
 - Because, it interesting to run some tests (eg Travis), you can run tests in the Container, then tests check the build, and check the code work in the future prod environment), you can cache the image, permit to run test faster (you also can do some cache on your Travis testing, but do all the recipe in Travis for install PHP dependencies, just for test... arf)
 - Because you use Travis (or others), you can push your Dev repository, and you can build when push or tagged on master on your production repository.
 - Then, I like to use Docker on a server, just install it, configure user mapping, maybe create an AppArmor, for security. Then you don't need install: MySQL, Nginx, PHP. And when you have some projects with different versions... Ouch, its not really clean. Thanks Docker :D 
 - You can Deploy automatically or not. Just a Docker compose, a named volume for upload, and it's done. When you want to update ? Just change the version, force re-build, updated :-)
 - You also can test easily an update of version. On your staging environment, you pull your previous version, install it (easy), try to update to the new one. If it works, it works (95% ? Maybe ?) on the production to.
 - Change version just with the ports: previous image on 8080, new one on 8081, configure HaProxy, and you can pass to the other easily. (It's almost the same without docker... you're right). 
 - In PHP, you can set the Memory limit for a Worker, in the config there is many Workers, CPU is most difficult. Idem for Nginx. In the container it's easy, you can set a CPU, Memory limit for each.
 - If a day you would like to use a tier service, AWS, Azure, change server, it's easier to switch with a docker container.
 - I think there is a lot of good reasons to use Docker, but it's some example. (maybe some repetitions... Sorry :/)

In my case, I think it's easier to configure the container, to change a version of a daemon, as a dependencies, and not do it on the Server. Maybe a dependencies is just needed for one project, maybe you fail on the installation, or forget that when deploy the new version. With docker, if it works in dev, it works in prod. I don't like install dependencies on my laptop: no php, no nginx, no mysql, no elasticsearch, redis, ... Just Docker and HaProxy, and the same on server.

I hope my answer will answer your questions.

**Comment by MrGabigoo** [comment]
Thanks for your explanations and examples @mpiot!

I have to admit the idea of reproductible builds between the `dev,` `staging `and `prod` environments are indeed a very strong argument in favor of Docker. All of the examples you give are good ways of making the most of containerization, which in essence I completely agree with.

Despite that, the only real downside of all this is the extremely sudden jump in implementation complexity, which requires a considerable amount of time to properly research, test and fully understand and know how to set up. I'm sure it's worthwile in the long run, much like it is for learning how to use Vim (simply as an example, I don't want to start a Vim & Emacs debate), but I do feel like the amount of hype generated by Docker does in a way overshadow many real practical, example-focused tutorials and guides on the internet, as far as I've noticed, which just ends up making it that much harder to get started with it.

For an application like _intranetV3_ my gut feeling is that it makes sense to use Docker with it given the fact that it hasn't ever been pushed to production at this point and testing can still be done before attemting to roll it out, but I do believe that it might somewhat slow development in a way since it will require additional knowledge for anyone maintaining the project, which will take time to acquire. But again, I'm sure @Dannebicque is willing to take the time to learn Docker if it can benefit him in the long run.

Regarding performance and the overhead Docker requires, what have you experienced in dev or even production compared to a standard LEMP-type setup? Based solely on my own tests (which very well may be an inaccurate metric) I've noticed that no matter what I do a "dockerized" app will almost always run slower than it's pure-LEMP counterpart. What do you make of that?

Oh and thanks again for your answer :)

**Comment by mpiot** [comment]
You're welcome.

I've never done Benchmarks (not really difficult, install the same version, same config, just not take the time). But I'm sure that Containerized app will be slower. Because you have a Docker Engine and a Lib mount between Containers. But, finally, you gain amount of time when you develop and deploy, and this loss of performance would mainly impact large applications. Which they would also deserve a containerization to create replicates anyway.

For the Development time, it's like Framework, you loss time to learn, you earn time to use :-) Finally, Docker is not really complex, maybe create a nice Dockerfile, docker-compose, Makefile, etc... is time consuming. But when it's done, it's pretty easy to maintain (just a kind of bash recipe).  (In addition, the config is based on https://github.com/mpiot/docker4symfony, I'll update somethings often, then it's easy to get some update if needed). But not really useful, when you want to add an extension, you add it, you can change version, etc... When you have nothing, it's difficult, but when you have the config... It's not.

This PR is may appear important, because there is the Webpack usage included, with the relocation of many files.

Docker it's just:
 - 1 folder (whith 4 tiny files)
 - 4 files (2 bigs: Makefile (very easy to understand), and the Dockerfile (not really difficult, maybe the Multistage may be confusing at first glance))

Travis-ci:
 - 3 files (the logical for the Ci is maybe more difficult)

**Comment by MrGabigoo** [comment]
Okay gotcha, thanks!

I'll definitely check out your repo, it looks well tought out! I think I should spend a bit more time tinkering with Docker, it does really make a point for development and deployment strategies. 

And yes you're right, I have to admit the commits do probably make it look way more cumbersome than it actually is. Do you have any examples or tutorials in mind for learning Docker (other than the official docs, since that's probably what I'll be looking at in the first place) that you might recommend?

**Comment by mpiot** [comment]
Not really... I've learn it with the doc, and by looking at some Dockerfiles (Drupal, PHP, WordPress, En-Marche, ...). Then I compiled better and do some tests, after sometime or use, I've done my repo.

So... The Docker doc, Docker-compose, maybe watch some Dockerfiles.

Juste when you start to learn, you'll see very quickly: 1 service = 1 container. But... At this moment, you'll be thinking: "Powa... he doesn't have do that....". It's just a specificity for PHP and Nginx, it's really more convenient, and finally a better response to: a container must be stateless.

**Comment by MrGabigoo** [comment]
Thanks for the tip, for some reason I hadn’t considered checking other projects’ docker setups, I’ll definitely be doing that!

And sure, why not :)

**Pull request merged**
